package io.arrogantprogrammer.spiritanimals.mocker;

import java.util.List;

public class FeedbackService {

    public static final List<String> positives = List.of("I love your demo, you are the best!",
            "J'adore votre demo", "Fantastic demo, really clear and engaging!", "Impressive technology, well presented.", "The presenter was incredibly knowledgeable.", "Very innovative approach, loved it!", "The demo was concise and informative.", "Excellent use of visuals to explain the features.", "The interactive part was a great addition.", "Everything was demonstrated with great clarity.", "The demo flowed beautifully from start to finish.", "Really appreciated the depth of detail.", "The presentation was very professional.", "It was easy to follow along and understand.", "The features were well highlighted.", "Loved the enthusiasm of the presenter!", "The demo was both educational and entertaining.", "Great job at keeping the audience engaged.", "The Q&A session was very helpful.", "The technology looks very promising.", "I was impressed by the practical applications shown.", "The demo exceeded my expectations.", "Well organized and paced perfectly.", "The presenter answered all questions clearly.", "Loved the hands-on demonstration.", "Very impactful presentation, made a strong case.", "The demonstration was very persuasive.", "I feel much more informed after the demo.", "The live demonstration was particularly effective.", "Excellent engagement with the audience.", "The features demonstrated were exactly what I was hoping to see.", "The demo was very lively and kept my attention throughout.", "Great demonstration of the product’s capabilities.", "The presenter was very articulate and clear.", "I’m really excited about the potential of this product.", "The demo was not only informative but also very inspiring.", "It was a perfect showcase of the product.", "The presentation was seamless and slick.", "I loved how the demo was tailored to the audience's needs.", "The demonstration was full of energy.", "Every feature was clearly explained and demonstrated.", "The presenter’s passion for the product was evident.", "I appreciated the comprehensive coverage of features.", "The demo was dynamic and interactive.", "Very professionally executed, top-notch demo.", "The demo provided a great overview of the product.", "I left feeling enthusiastic about the product’s possibilities.", "The presentation style was very engaging and effective.", "The technology demoed was cutting-edge.", "It was a thorough and compelling presentation.", "I loved the clarity and precision of the demo.", "The product came across as very user-friendly.", "The demonstration addressed all my concerns.", "Very exciting features were showcased.", "The demo was packed with useful information.", "It was a very persuasive demonstration of the product.", "The presenter made complex topics easy to understand.", "Loved the direct approach to presenting the product.", "The demo was lively and interactive.", "Fantastic pacing, not a dull moment.", "The demo was very polished and professional.", "It provided a clear understanding of the product.", "The demonstration was very thorough and detailed.", "I'm impressed by the innovative features shown.", "The product looks fantastic based on the demo.", "It was a very effective and enjoyable presentation.", "The presenter was charismatic and informative.", "The demo did a great job of highlighting key benefits.", "I'm convinced of the product's value after the demo.", "The demonstration was perfectly executed.", "The interactive elements were a great touch.", "Very clear explanations, great demo!", "The presenter was engaging and well-prepared.", "Loved the practical demonstrations of the product.", "The demo highlighted the product's strengths very well.", "It was a compelling showcase of the product’s features.", "The presenter handled all questions with ease.", "I’m excited to see the next steps after this demo.", "The demo was very impactful and memorable.", "Great balance between detail and overview.", "The demonstration gave me confidence in the product.", "I was captivated by the demo from beginning to end.", "The presentation was very clear and well thought out.", "The demo showed off some impressive technology.", "It was a very insightful and enlightening demonstration.", "The presenter’s expertise was clear.", "I really enjoyed the interactive format of the demo.", "The product seems very user-friendly based on the demo.", "The demonstration was vibrant and full of energy.", "It was an excellent introduction to the product.", "The demo was thorough and very convincing.", "I appreciate how the features were demonstrated so clearly.", "The live demo aspect was particularly effective.", "I’m really impressed with what I saw today.", "The demonstration provided a deep dive into the product.", "The presentation was well structured and easy to follow.", "The presenter was very compelling and enthusiastic.", "I'm really looking forward to trying the product."            );

    public static final List<String> negatives = List.of("The demo felt rushed and incomplete.",
            "It was hard to follow the presenter's explanations.",
            "The technology seemed outdated.",
            "Not enough detail on the key features.",
            "The presenter lacked enthusiasm.",
            "Too much technical jargon used without explanations.",
            "The visuals were unclear and unhelpful.",
            "It lacked interactive elements.",
            "The demo did not cover all advertised features.",
            "Questions from the audience were not addressed well.",
            "The demonstration seemed disorganized.",
            "The pacing was too slow.",
            "Technical issues were distracting.",
            "It felt overly scripted and unnatural.",
            "The features were not demonstrated practically.",
            "Lacked real-world application examples.",
            "The demo was too generic with no unique selling points highlighted.",
            "The presenter seemed unprepared.",
            "Not engaging enough, I lost interest halfway through.",
            "No opportunity for hands-on interaction was provided.",
            "The presenter spoke too softly, hard to hear.",
            "The demo did not live up to the hype.",
            "It was all theoretical with no demonstrations.",
            "Failed to explain the benefits clearly.",
            "The presentation lacked depth.",
            "Too much time spent on unimportant features.",
            "The demo ended abruptly without a proper conclusion.",
            "The presenter didn't seem knowledgeable.",
            "The environment was not conducive for a demo.",
            "Feedback from the audience was not solicited.",
            "The product seemed unreliable during the demo.",
            "There was no clear structure to the presentation.",
            "Key features were glossed over too quickly.",
            "The demo lacked professionalism.",
            "Poor audio quality made it difficult to understand.",
            "The presenter was monotone and boring.",
            "The demo was too long and drawn out.",
            "No follow-up information was provided.",
            "The user interface shown was not user-friendly.",
            "It failed to demonstrate the product's value.",
            "Lacked clear answers to important questions.",
            "The product did not perform as expected during the demo.",
            "Missed opportunities to show product's full potential.",
            "The presenter frequently went off-topic.",
            "The demo did not include any comparisons to other products.",
            "No examples of success stories or case studies.",
            "The product's impact on existing systems was not addressed.",
            "The presenter seemed to dodge difficult questions.",
            "It felt like a sales pitch rather than an informative demo.",
            "The transitions between topics were confusing.",
            "There was too much emphasis on less important aspects.",
            "Not enough visuals to support the claims.",
            "The demonstration lacked energy.",
            "It did not build a strong case for the product.",
            "The benefits of the product were not effectively communicated.",
            "There was a lack of enthusiasm from the presenter.",
            "The demo did not showcase the product effectively.",
            "Failed to address key market needs.",
            "The demo was redundant and repetitive.",
            "The presenter mispronounced important terms.",
            "It was difficult to see the presentation due to poor lighting.",
            "The presenter's explanations were too complex.",
            "Not enough background information was provided.",
            "The demo was too technical for a general audience.",
            "The presentation did not use the allotted time wisely.",
            "There were factual errors in the presentation.",
            "The demo felt impersonal and detached.",
            "The presenter relied too much on notes.",
            "There was no clear call to action.",
            "The demonstration did not instill confidence in the product.",
            "The information provided was outdated.",
            "There was no mention of future developments.",
            "The demo lacked critical information.",
            "It was more about the company than the product.",
            "The presenter avoided answering key questions directly.",
            "The demonstration lacked a clear target audience.",
            "It seemed like the product had limited applicability.",
            "The demo did not highlight any competitive advantages.",
            "The presentation style was not appealing.",
            "The product features were not well integrated into the demo.",
            "There was no interaction with the audience.",
            "The demo lacked originality.",
            "The presentation was filled with clichés.",
            "The product seemed complicated to use.",
            "The demo did not make a compelling argument for the product.",
            "The presenter lacked confidence.",
            "There were too many assumptions made without explanations.",
            "The demo did not provide enough statistical evidence.",
            "There was a lack of focus in the presentation");

    public static final List<String> neutrals = List.of("The demo was as expected.",
            "There were no surprises in the presentation.",
            "It covered the basics of the product.",
            "The presenter was clear, though not particularly engaging.",
            "The technology was demonstrated without much fanfare.",
            "It provided a standard overview of the features.",
            "The pacing of the demo was average.",
            "There were no technical issues, but nothing stood out either.",
            "The content of the demo was adequate.",
            "The demonstration was straightforward.",
            "The product seems okay, neither impressive nor disappointing.",
            "The presenter stuck to the script without adding personal insights.",
            "It was a typical demo, nothing more, nothing less.",
            "The presentation style was neutral.",
            "The demo did not go beyond what was necessary.",
            "Basic functionality was covered as expected.",
            "The presentation met the minimal requirements.",
            "The demo was neither thorough nor lacking.",
            "It provided enough information to get a general idea.",
            "The presenter maintained a professional demeanor.",
            "The product was shown but not explored in depth.",
            "The demo had a standard length.",
            "There was a reasonable amount of detail provided.",
            "The demonstration followed a predictable format.",
            "The presentation neither exceeded nor fell short of expectations.",
            "The product features were listed without extensive demonstration.",
            "The visuals were standard and functional.",
            "There was an average amount of interaction with the audience.",
            "The presenter answered questions but didn't elaborate much.",
            "The demo included basic examples of the product in use.",
            "The information was presented in a neutral tone.",
            "The demonstration was done competently.",
            "It was a routine run-through of the product's capabilities.",
            "The technology seems reliable but not groundbreaking.",
            "The presentation was methodical.",
            "The demo was delivered without any impactful moments.",
            "The functionality demonstrated was as expected with no extras.",
            "The presenter's approach was conventional.",
            "It was an adequate demonstration of the product's current state.",
            "The presentation provided necessary information with no additional insights.",
            "The demo was done in an orderly fashion.",
            "The presentation was what one would typically expect.",
            "The product's performance was standard, nothing unusual.",
            "The features were explained at a surface level.",
            "There were no significant issues, but also no highlights.",
            "The demo was completed in a timely manner.",
            "The presentation was factual without being detailed.",
            "The demo served as a basic introduction to the product.",
            "The presenter was neither particularly persuasive nor unconvincing.",
            "The information given was sufficient for a basic understanding.",
            "The demonstration was plain and to the point.",
            "There was a balanced amount of technical and general information.",
            "The demo did not delve deeply into any particular feature.",
            "The presentation maintained a steady pace throughout.",
            "The product was shown in a typical usage scenario.",
            "The presenter maintained a neutral tone throughout the demo.",
            "The demo was performed competently with standard execution.",
            "There were no deviations from the expected demo structure.",
            "The presentation was clear but lacked depth.",
            "The product's capabilities were shown but not explored in depth.",
            "The demo was a straightforward depiction of the product.",
            "The presenter provided the necessary information as required.",
            "It was an average presentation with no unique aspects.",
            "The demonstration adhered to the basic format.",
            "The presenter was effective but not memorable.",
            "The product was displayed adequately.",
            "The demo was functional but not inspiring.",
            "There were no major faults, yet nothing distinguished the demo.",
            "The demonstration was consistent with industry standards.",
            "The presenter covered the essential points.",
            "The product seems to work as intended, but no more.",
            "The demonstration did not provide a deep dive into any area.",
            "The visuals supported the presentation without enhancing it.",
            "The presentation was neutral, with no strong opinions expressed.",
            "The demo showed the product's basic functionality.",
            "The presenter was clear but not engaging.",
            "The demonstration covered all necessary points without going beyond.",
            "The demo was done to an acceptable standard.",
            "The presentation gave a fair overview of the product.",
            "The product was demonstrated with standard proficiency.",
            "The information provided was what would be expected from such a demo.",
            "The demonstration was neither detailed nor too brief.");

    public static String getRandomButMostlyPositiveFeedback() {
        if (randomNumberBetweenOneAndTen() % 3 > 0) {
            return getPositiveFeedback();
        } else if (randomNumberBetweenOneAndTen() % 3 > 0) {
            return getNegativeFeedback();
        } else {
            return getNeutralFeedback();
        }
    }

    private static int randomNumberBetweenOneAndTen() {
        return (int) (Math.random() * 10) + 1;
    }

    public static String getPositiveFeedback() {
        return positives.get((int) (Math.random() * positives.size()));
    }

    public static String getNegativeFeedback() {
        return negatives.get((int) (Math.random() * negatives.size()));
    }

    public static String getNeutralFeedback() {
        return neutrals.get((int) (Math.random() * neutrals.size()));
    }
}
