package io.arrogantprogrammer.spiritanimals.mocker;

import java.util.Arrays;
import java.util.List;

public class NameService {

    public static final List<String> names = Arrays.asList(
            "Michael", "James", "John", "Robert", "David", "Mary", "Patricia", "Jennifer", "Linda", "Elizabeth", "William", "Richard", "Joseph", "Charles", "Thomas", "Christopher", "Daniel", "Matthew", "Anthony", "Mark", "Donald", "Steven", "Paul", "Andrew", "Joshua", "Kenneth", "Kevin", "Brian", "George", "Edward", "Ronald", "Timothy", "Jason", "Jeffrey", "Ryan", "Barbara", "Nancy", "Karen", "Deborah", "Susan", "Jessica", "Sarah", "Sharon", "Michelle", "Lisa", "Betty", "Dorothy", "Sandra", "Ashley", "Kimberly", "Donna", "Emily", "Carol", "Amanda", "Melissa", "Deborah", "Stephanie", "Rebecca", "Laura", "Sharon", "Cynthia", "Heather", "Amy", "Angela", "Anna", "Brenda", "Pamela", "Nicole", "Samantha", "Katherine", "Emma", "Elizabeth", "Brooke", "Allison", "Alexis", "Natalie", "Grace", "Hannah", "Julia", "Megan", "Laura", "Lauren", "Evelyn", "Alice", "Madison", "Ava", "Charlotte", "Mia", "Isabella", "Harper", "Amelia", "Evelyn", "Abigail", "Emily", "Ella", "Madison", "Scarlett", "Victoria", "Aria", "Grace", "Chloe", "Camila", "Penelope", "Riley",
            "Luca", "Sofia", "Hugo", "Isla", "Oliver", "Amelia", "Harry", "Ava", "Oscar", "Isabella", "George", "Mia", "Noah", "Lily", "Jack", "Olivia", "Charlie", "Emily", "Jacob", "Sophia", "Alfie", "Ella", "Freddie", "Grace", "Ethan", "Evie", "William", "Charlotte", "James", "Sienna", "Leo", "Alice", "Alexander", "Scarlett", "Henry", "Ivy", "Archie", "Jessica", "Joseph", "Sophie", "Arlo", "Ruby", "Thomas", "Daisy", "Oscar", "Chloe", "Max", "Matilda", "Arthur", "Rosie", "Theo", "Phoebe", "Logan", "Elsie", "Benjamin", "Poppy", "Harrison", "Layla", "Edward", "Millie", "Lucas", "Esme", "Finley", "Eliza", "Isaac", "Georgia", "Mason", "Zoe", "Dexter", "Molly", "Liam", "Erin", "Teddy", "Eleanor", "Daniel", "Harriet", "Samuel", "Rose", "Sebastian", "Nancy", "Jake", "Mabel", "Louis", "Emma", "Rhys", "Holly", "Elliot", "Thea", "Matthew", "Lola", "Toby", "Imogen", "Caleb", "Freya", "Gabriel", "Summer", "Adam", "Darcie", "Rory", "Lottie", "Nathan", "Lara", "Harvey", "Millie",
            "Haruto", "Yumi", "An", "Lin", "Hiroshi", "Akira", "Kenji", "Sato", "Takashi", "Yuji", "Naoki", "Yoshio", "Kaito", "Yuto", "Haruki", "Ren", "Shota", "Kyo", "Masato", "Shinji", "Hiro", "Jun", "Daiki", "Riku", "Kazuya", "Sho", "Makoto", "Yuki", "Takuya", "Sora", "Hotaru", "Sakura", "Nana", "Akane", "Yoko", "Sayuri", "Emiko", "Aiko", "Kyoko", "Saki", "Arata", "Mei", "Chinatsu", "Hana", "Yua", "Nozomi", "Ayumi", "Mio", "Rina", "Miho", "Kaori", "Kana", "Asami", "Rei", "Mai", "Eri", "Riko", "Manami", "Mari", "Yuna", "Momoko", "Shiori", "Aya", "Yuko", "Hikari", "Nanami", "Keiko", "Yoshiko", "Noriko", "Masami", "Sachiko", "Tomoko", "Haruna", "Ayaka", "Sayaka", "Mika", "Chiaki", "Naomi", "Minami", "Rie", "Asuka", "Akiko", "Yuri",
            "Sofia", "João", "Lucía", "Santiago", "Valentina", "Sebastián", "Martina", "Leonardo", "Isabella", "Benjamin", "Emma", "Matías", "Lucía", "Andrés", "Camila", "Nicolás", "Victoria", "Samuel", "Catalina", "Gabriel", "Valeria", "Diego", "Daniela", "Alejandro", "Mariana", "Felipe", "Sara", "Ángel", "Paula", "Tomás", "Carla", "Juan", "Elena", "Luis", "Ana", "Pablo", "Alejandra", "Carlos", "Andrea", "Roberto", "María", "José", "Leticia", "Fernando", "Sofía", "Miguel", "Natalia", "Jorge", "Gabriela", "Ramón", "Francisca", "Manuel", "Constanza", "Eduardo", "Antonella", "Rafael", "Julieta", "Mario", "Emilia", "Alvaro", "Micaela", "Hector", "Miranda", "Gustavo", "Josefina", "Ricardo", "Florencia", "Antonio", "Maite", "Iván", "Lorena", "César", "Regina", "Omar", "Cecilia", "Dante", "Agustina", "Enrique", "Jimena", "Bruno", "Valentina", "Salvador", "Zoe",
            "Aarav", "Aditi", "Ajay", "Akash", "Akhil", "Alok", "Amit", "Amrita", "Ananya", "Anil", "Anita", "Anjali", "Arjun", "Aryan", "Asha", "Ashok", "Asmita", "Avinash", "Balraj", "Bhavna", "Chandra", "Deepa", "Deepak", "Dinesh", "Divya", "Gaurav", "Geeta", "Govind", "Harish", "Harpreet", "Isha", "Ishan", "Jai", "Jyoti", "Kailash", "Kajal", "Kalyan", "Kamal", "Karan", "Kavita", "Kiran", "Krishna", "Lalita", "Lata", "Lavanya", "Madhav", "Madhu", "Mahesh", "Malini", "Manish", "Manoj", "Meena", "Meera", "Mohan", "Mukesh", "Nalini", "Namita", "Naveen", "Neel", "Neha", "Nikhil", "Nina", "Nitin", "Om", "Pankaj", "Parvati", "Pooja", "Prakash", "Pranav", "Priya", "Rahul", "Raj", "Rakesh", "Rani", "Ranjit", "Ravi", "Rekha", "Renu", "Rohan", "Rohit", "Rupa", "Sagar", "Sahil", "Sameer", "Sandeep", "Sanjay", "Sanjeev", "Santosh", "Sarita", "Saurabh", "Seema", "Shalini", "Shankar", "Shanti", "Shruti", "Sunita", "Suraj", "Suresh", "Usha", "Vijay"
    );

    public static String getName() {
        return names.get((int) (Math.random() * names.size()));
    }
}
